### ISSUE TITLE
Issues with leading zeros in coordinates

### ISSUE THREAD

**Issue by jonesmg** [pndaly/mgui#1]
This is not urgent now as few of my current targets have problematic coordinates, but I had trouble still we some declination values e.g. "-08:50:00.0" and "+09:47:00.0"

**Comment by pndaly** [comment]
I upgraded the regexp handler and it returns 1 (true, ok) when I do the following:

% cd mgui/src
% tclsh
source mguiRADec.tcl
% checkDec -08:50:00.0
1
% checkDec +09:47:00.0
1
% exit

Do a git pull and see if the problem goes away. You can also do a 'testCheckRADec' (within tclsh as above) and see what
syntax is now supported.

**Comment by jonesmg** [comment]
The testCheckRADec gave the expected results:

`RA 12:34:56.7 is OK
RA 12:34:56.70 is OK
RA 12:34:56.702 is OK
RA 2:34:56.7 is OK
RA 2:34:56.70 is OK
RA 2:34:56.702 is OK
RA 02:34:56.7 is OK
RA 02:34:56.70 is OK
RA 02:34:56.702 is OK
RA 22:34:56.7 is OK
RA 22:34:56.70 is OK
RA 22:34:56.702 is OK
ERROR: RA 24:00:00.000 is NOT OK
Dec 12:34:56.7 is OK
Dec 12:34:56.70 is OK
Dec 12:34:56.702 is OK
Dec 2:34:56.7 is OK
Dec 2:34:56.70 is OK
Dec 2:34:56.702 is OK
Dec 02:34:56.7 is OK
Dec 02:34:56.70 is OK
Dec 02:34:56.702 is OK
Dec -12:34:56.7 is OK
Dec -12:34:56.70 is OK
Dec -12:34:56.702 is OK
Dec -2:34:56.7 is OK
Dec -2:34:56.70 is OK
Dec -2:34:56.702 is OK
Dec -02:34:56.7 is OK
Dec -02:34:56.70 is OK
Dec -02:34:56.702 is OK
ERROR: Dec 90:00:00.000 is NOT OK
ERROR: Dec -90:00:00.000 is NOT OK`

However, it still causes problems in the gui. A declination of "+09:47:00.0" resulted in an error message and an empty output tsv file.

<img width="653" alt="Screenshot 2023-04-20 172041" src="https://user-images.githubusercontent.com/10732417/233513038-ef08cb6d-3fbe-4408-a5a8-c907e3b11822.png">

If I remove the leading zero then it does produce an output file, but the declination values are incorrect.

<img width="549" alt="Screenshot 2023-04-20 172224" src="https://user-images.githubusercontent.com/10732417/233513133-4da58749-37d3-4f17-9a85-c2a96a3b8e7d.png">
